phy_bin <- read.table("ll_models/bin/cv_acc.txt", header=T)
phy_count <- read.table("ll_models/norm/cv_acc.txt", header=T)
g3l1 <- read.table("parsimony/models_g2_l1/cv_acc.txt", header=T)
g2l1 <- read.table("parsimony/models_g3_l1/cv_acc.txt", header=T)

png("parsimony/bacc.png")
plot(x=c(0,max(nrow(phy_bin),nrow(phy_count),nrow(g3l1),nrow(g2l1))),type='n', y=c(0,1), xlab="index", ylab="balanced accuracy")
lines(seq(1,nrow(phy_bin)),sort(decreasing=T,phy_bin[,4]), col="green")
lines(seq(1,nrow(phy_count)),sort(decreasing=T,phy_count[,4]), col="red")
lines(seq(1,nrow(g3l1)),sort(decreasing=T,g3l1[,4]), col="blue")
lines(seq(1,nrow(g2l1)),sort(decreasing=T,g2l1[,4]), col="black")
legend("topright",legend=c( "phy bin", "phy count", "gg3l1","gg2l1"), col = c("green", "red", "blue","black"), lwd=1) 
dev.off() 

accs <- list(phy_bin, phy_count, g3l1, g2l1)
names <- c("phy bin", "phy count", "gg3l1", "gg2l1")
sapply(seq(1,4), function(x){
    png(paste("parsimony/acc_",names[x],".png", sep=""))
    plot(x=c(0,nrow(accs[[x]])) ,y=c(0,1),type='n', xlab="index")
    lines(seq(1, nrow(accs[[x]])), accs[[x]][,2][order(accs[[x]][,4], decreasing=T)], col="green")
    lines(seq(1, nrow(accs[[x]])), accs[[x]][,3][order(accs[[x]][,4], decreasing=T)], col="red")
    lines(seq(1, nrow(accs[[x]])), sort(decreasing=T,accs[[x]][,4]), col="blue")
    legend("topright",legend=c("pos recall", "neg recall", "bacc"), col = c("green", "red", "blue"), lwd=1) 
    dev.off()
})
